package raf.thesis.metadata.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field in {@link Entity} class to specify that it is a part of the primary key.
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface Id {
    /**
     * Determines if the primary key is generated by the DB.
     * @return {@code true} if key is generated, {@code false} if not
     */
    boolean generated() default false;
}
